debug:
  logLevel: info
  flushLevel: trace

perks:
  # Perk to enable apprentice quality potions
  level2: Skyrim.esm|BE127
  # Perk to enable adept quality potions
  level3: Skyrim.esm|C07CA
  # Perk to enable expert quality potions
  level4: Skyrim.esm|C07CB
  # Perk to enable master quality potions
  level5: Skyrim.esm|C07CC
  # Perk to make potions +1 quality
  potionQuality: Skyrim.esm|58216
  # Perk to make poisons +1 quality
  poisonQuality: Skyrim.esm|58217
  # Perk to make both potions & poisons +1 quality
  allQuality: Skyrim.esm|5821D
  # Perk to increase produced potions & poisons by +1 (not exist in vanilla game but perks overhaul often adds it)
  doubleItems:

ingredients:
  addRaritySuffix: true
  commonSuffix: (Common)
  uncommonSuffix: (Uncommon)
  rareSuffix: (Rare)
